export const HANDLE_SUBMIT = 'HANDLE_SUBMIT';
export const HANDLE_FILTER = 'HANDLE_FILTER';
export const HANDLE_FORM_INPUT = 'HANDLE_FORM_INPUT';
export const HANDLE_FORM_CHECKED = 'HANDLE_FORM_CHECKED';
export const HANDLE_FORM_DATE = 'HANDLE_FORM_DATE';
export const HANDLE_TABLE_DATA = 'HANDLE_TABLE_DATA';
