export const HANDLE_SUBMIT = 'HANDLE_SUBMIT';
export const HANDLE_FILTER = 'HANDLE_FILTER';
export const HANDLE_FORM_EDIT = 'HANDLE_FORM_EDIT';
export const HANDLE_FORM_CHECKED = 'HANDLE_FORM_CHECKED';
export const HANDLE_FORM_UPDATE = 'HANDLE_FORM_UPDATE';

